version: '3.8'

services:
  # Backend для разработки
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pgu-map-backend-dev
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend_dev_data:/app/data
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=sqlite:///data/university_map.db
      - FASTAPI_ENV=development
    networks:
      - pgu-dev-network
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  # Frontend для разработки
  frontend-dev:
    image: node:18-alpine
    container_name: pgu-map-frontend-dev
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app
      - /app/node_modules
    working_dir: /app
    environment:
      - NODE_ENV=development
    networks:
      - pgu-dev-network
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    depends_on:
      - backend-dev

volumes:
  backend_dev_data:
    driver: local

networks:
  pgu-dev-network:
    driver: bridge 